#!/usr/bin/env bash

# clean old time machine backups

read -e -p "Enter Year: " year
read -e -p "Enter Month: " month
month=$(printf %02d $month)
read -e -p "Remove all backups in $year-$month? [y/n] "
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

for i in /Volumes/TM/Backups.backupdb/rmbpro/$year-$month* ;
    do tmutil delete "$i" ;
done
