#!/usr/bin/env bash
# modified from https://gist.github.com/drewbarontini/be4b130c3a7412c84b77

tag=$(git describe --abbrev=0 --tags 2>/dev/null)
prefix=$(echo $tag | grep -o --color=never "[A-z]\+")
major=$(echo $tag | cut -d '.' -f1 | grep -o --color=never "[0-9]")
minor=$(echo $tag | cut -d '.' -f2)
patch=$(echo $tag | cut -d '.' -f3)

case "$1" in
    'major')
      nmajor=$(($major+1))
      version="$nmajor.0.0"
      ;;
    'minor')
      nminor=$(($minor+1))
      version="$major.$nminor.0"
      ;;
    'patch')
      npatch=$(($patch+1))
      version="$major.$minor.$npatch"
      ;;
    *)
      echo "Automatically set a git tag based on Semantic Versioning keyword"
      echo
      echo "Usage: git publish <major|minor|patch>"
      echo
      echo "Example:"
      echo "  git publish major"
      echo
      echo "If this is your first tag, use 'git tag' to set up your first one."
esac

if [[ "$version" ]]
then
    git tag -a "$prefix$version" -m "Version $version"
    echo "$prefix$version created!"
fi
