#!/usr/bin/env bash

read -e -p "Enter Repo name: " myrepo
read -e -p "Enter User: " myuser
ret=$(curl -s --user "$myuser" https://api.github.com/user/repos -d '{"name":"'"$myrepo"'"}')
gitaddress=$(echo "$ret" | grep ssh_url | awk '{print $2}' | sed 's/"\(.*\)",/\1/')

if [[ -z $gitaddress ]]; then
    echo "$ret"
    exit 1
else
    echo "$gitaddress"
fi
read -e -p "git init here? [y/n] "
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

st=$(git status 2>/dev/null | head -n 1)
if [[ $st == "" ]]; then
    git init
fi
st=$(git status 2>/dev/null | head -n 1)
rt=$(git remote 2>/dev/null | grep origin)
if [[ $st != "" ]] && [[ $rt == "" ]]; then
    git remote add origin $gitaddress
fi
