#! /usr/bin/env bash

set -e

curl -L https://julialangnightlies-s3.julialang.org/bin/mac/x64/julia-latest-mac64.dmg -o ~/Downloads/julia.dmg
hdiutil attach ~/Downloads/julia.dmg
cd /Volumes/Julia*/Julia*/Contents/Resources
rm -rf /opt/local/julia-dev
cp -r julia /opt/local/julia-dev
# diskutil umount force /Volumes/Julia*
hdiutil detach -force /Volumes/Julia*
rm -rf ~/Downloads/julia.dmg
