#!/usr/bin/env bash

# clean old time machine backups

set -e

while [ "$#" -ne 0 ]; do
    key="$1"
    case "$key" in
        --help|-h)
            echo "usage: tm-clean [--year= ] [--month= ] [--force]"
            exit 1
        ;;
        --year)
            year="$2"
            shift 2
        ;;
        --month)
            month="$2"
            shift 2
        ;;
        --force)
            force=true
            shift 1
        ;;
        *)
            echo "Unknown option: $1"
            exit 1
        ;;
    esac
done

[[ -z "$year" ]] && read -e -p "Enter Year: " year
if [[ -z "$month" ]]; then
    read -e -p "Enter Month: " month
fi

month=$(printf %02d $month)

if [[ -z "$force" ]]; then
    read -e -p "Remove all backups in $year-$month? [y/n] "
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

for i in ./$year-$month* ;
    do tmutil delete "$i" ;
done
