#!/bin/sh
export PATH=$PATH:/usr/local/bin
[ "$TMUX" == "" ] || exit 0


get_sessions()
{
    echo $(tmux list-sessions -F "#S" 2>/dev/null)
}

create_default_session()
{
    tmux has-session -t _default 2>/dev/null || tmux new-session -s _default -d
}

kill_session()
{
    sessions=($(get_sessions))
    [[ -z $sessions ]] && exit

    # PS3="session to kill: "
    echo ""
    echo "kill-session"
    echo "---------------------"

    select opt in "${sessions[@]}"
    do
        case "$opt" in
            *)  
                [[ -z "$opt" ]] && continue
                
                read -e -p "kill $opt? [y/n] "
                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    tmux kill-session -t $opt 2>/dev/null
                fi
                [ "$?" -eq 0  ] && kill_session
                ;;
        esac
    done
}

main_menu()
{
    # options=("[new session]" "[kill session]" "[shell]")
    options=("[new session]" "[kill session]")
    sessions=$(get_sessions)
    [ ! -z $session ] || options=($sessions "${options[@]}")

    echo "tmux sessions:"
    echo "---------------------"
    PS3="option: "

    select opt in "${options[@]}"
    do
        case "$opt" in
            "[new session]")
                read -e -p "new session name: " SESSION_NAME
                tmux new -s "$SESSION_NAME" 2>/dev/null
                [ "$?" -eq 0  ] || tmux new
                break
                ;;
            "[shell]")
                zsh --login
                break
                ;;
            "[kill session]")
                kill_session
                break
                ;;
            *)
                tmux attach-session -t $opt 2>/dev/null
                [ "$?" -eq 0  ] && break
                ;;
        esac
    done
}

create_default_session
main_menu
